elice_library/views/comment_views.py
from datetime import datetime
from flask import Blueprint, url_for, request, render_template, g, flash
from werkzeug.utils import redirect

from elice_library import db
from elice_library.forms import CommentForm
from elice_library.models import Book, Comment
from elice_library.views.auth_views import login_required

bp = Blueprint('comment', __name__, url_prefix='/comment')

@bp.route('/create/book/<int:book_id>', methods=('GET', 'POST'))
@login_required
def create_comment(book_id):
    form = CommentForm()
    book = Book.query.get(book_id)
    if request.method == 'POST' and form.validate_on_submit():
        comment = Comment(user=g.user, content=form.content.data, create_date=datetime.now(), book=book)
        db.session.add(comment)
        db.session.commit()
        return redirect(url_for('main.book', book_id=book_id))
    return render_template('comment/comment_form.html', form=form)

@bp.route('/modify/<int:comment_id>', methods=('GET', 'POST'))
@login_required
def modify(comment_id):
    comment = Comment.query.get_or_404(comment_id)
    book_info = comment.book
    book_id = book_info.id
    if g.user != comment.user:
        flash('수정권한이 없습니다')
        return redirect(url_for('main.book', id=comment.book.id))
    if request.method == 'POST':
        form = CommentForm()
        if form.validate_on_submit():
            form.populate_obj(comment)
            rating = request.form['rating']
            comment.rating = rating
            comment.modify_date = datetime.now()  # 수정일시 저장
            comment_all = Comment.query.filter(Comment.book==book_info)
            comment_len = Comment.query.filter(Comment.book==book_info).all()
            rating_all = 0
            for comment_each in comment_all:
                rating_all += int(comment_each.rating)
            rating_portion = rating_all//len(comment_len)
            rating_rest = rating_all/len(comment_len) - rating_portion
            if rating_rest >= 0.5:
                rating_rest = 1
            else:
                rating_rest = 0
            book_info.rating = rating_portion + rating_rest
            db.session.commit()
            return redirect('{}#comment_{}'.format(url_for('main.book', id=book_id), comment.id))
            # return redirect(url_for('main.book', id=comment.book.id))
    else:
        form = CommentForm(obj=comment)
    comment_all = Comment.query.filter(Comment.book==book_info)
    comment_len = Comment.query.filter(Comment.book==book_info).all()
    rating_all = 0
    for comment_each in comment_all:
        rating_all += int(comment_each.rating)
    if len(comment_len) == 0:
        rating_avg = 0
    else:
        rating_avg = rating_all/len(comment_len)
    return render_template('bookinfo.html', book_info=book_info, form=form, rating_avg=rating_avg)

@bp.route('/delete/<int:comment_id>')
@login_required
def delete(comment_id):
    comment = Comment.query.get(comment_id)
    book_id = comment.book.id
    book_info = Book.query.filter(Book.id==book_id).first()
    if g.user != comment.user:
        flash('삭제권한이 없습니다')
        return redirect(url_for('main.book', id=book_id))
    db.session.delete(comment)
    comment_all = Comment.query.filter(Comment.book==book_info)
    comment_len = Comment.query.filter(Comment.book==book_info).all()
    rating_all = 0
    for comment_each in comment_all:
        rating_all += int(comment_each.rating)
    rating_portion = rating_all//len(comment_len)
    rating_rest = rating_all/len(comment_len) - rating_portion
    if rating_rest >= 0.5:
        rating_rest = 1
    else:
        rating_rest = 0
    book_info.rating = rating_portion + rating_rest
    db.session.commit()
    return redirect('{}#comment_{}'.format(url_for('main.book', id=book_id), comment.id))
    # return redirect(url_for('main.book', id=book_id))

elice_library/templates/back.html
{% extends 'base.html' %}
{% block content %}
<main>
    <div class="album py-5 bg-light">
        <div class="container">
    
          <div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 g-3">
            {% for rental_info in rental_list %}
            {% if rental_info.return_date == None %}
            <div class="col" style="width:25%;">
              <div class="card shadow-sm" style="height:90%">
                <img src="{{ rental_info.book.image_path }}" style="height:70%;">
                <div class="card-body" style="height:30%;">
                  <p class="card-text" style="height:40%;"><a href="/book/{{ rental_info.book_id }}">{{ rental_info.book.bookname }}</a></p>
                  <div class="d-flex justify-content-between align-items-center">
                    <div class="btn-group">
                      <form action = "/back" method="POST">
                        <input type="hidden" name = "id" value = "{{ rental_info.id }}">
                        <button class="btn btn-sm btn-outline-secondary">반납하기</button>
                        <!-- <button>요소 자체는 submit속성을 지니고 있기 때문에 type 정의가 되어있지 않다면 submit 동작을 한다. -->
                      </form>
                    </div>
                    
                    <small class="text-muted">대여일자 : {{ rental_info.rental_date|datetime }}</small>
                  </div>
                </div>
              </div>
            </div>
            {% endif %}
            {% endfor %}
          </div>
        </div>
      </div>
</main>
{% endblock %}

elice_library/templates/base.html
<!DOCTYPE html>
<html lang="ko">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="canonical" href="https://getbootstrap.com/docs/5.0/examples/album/">
    <link rel="stylesheet" href="{{ url_for('static', filename='css/star.css') }}">
    <link rel="stylesheet" href="{{ url_for('static', filename='css/tailwind.min.css') }}">
    <link rel="stylesheet" href="{{ url_for('static', filename='css/bootstrap.min.css') }}">
    <link rel="stylesheet" href="{{ url_for('static', filename='css/style.css') }}">
    <link rel="stylesheet" href="{{ url_for('static', filename='css/slide.css') }}">
    <title>레이서 도서관</title>
    <style>
        .bd-placeholder-img {
          font-size: 1.125rem;
          text-anchor: middle;
          -webkit-user-select: none;
          -moz-user-select: none;
          user-select: none;
        }
        @media (min-width: 768px) {
          .bd-placeholder-img-lg {
            font-size: 3.5rem;
          }
        }
      </style>
</head>
<body>
    <header>
      <!-- 네비게이션바 -->
        <div class="navbar navbar-dark bg-dark shadow-sm">
          <div class="container">
            <div style="width:10%;">
              <a href="/" style="color:#ffffff"><strong>엘리스 도서관</strong></a>
            </div>
            <div style="width:90%;text-align:right;">
              {% if admin_id == 1 %}
                <a class="btn btn-outline-primary" href="/auth/user">관리자모드</a>
              {% endif %}
              <a class="btn btn-outline-primary" href="/auth/logout">로그아웃</a>
              <a class="btn btn-outline-primary" href="/rental">대여목록</a>
              <a class="btn btn-outline-primary" href="/back">반납하기</a>
              <ul class="nav nav-tabs" style="display:inline-block;">
                <li class="nav-item dropdown" style="display: inline-block;">
                  <a class="nav-link dropdown-toggle" data-bs-toggle="dropdown" href="#" role="button" aria-expanded="false" style="display: inline-block;color:white;padding:.375rem .75rem;">My Page</a>
                  <ul class="dropdown-menu">
                    <li><a class="dropdown-item" href="/mypage/info">회원정보</a></li>
                    <li><a class="dropdown-item" href="/mypage/comment">리뷰일지</a></li>
                    <li><a class="dropdown-item" href="/mypage/rental">대여기록</a></li>
                  </ul>
                </li>
              </ul>
            </div>
          </div>
        </div>
      <!-- 네비게이션 바 End -->
    </header>
    {% block content %}
    {% endblock %}
    <footer class="text-muted py-5">
        <div class="container">
          <p class="float-end mb-1">
            <a href="#">Back to top</a>
          </p>
          <p class="mb-1">Copyright 2021 엘리스 Inc. All rights reserved.</p>
          <p class="mb-0">Need information? <a href="/">Visit the homepage</a> or email <a href="/">ksy9926@naver.com</a></p>
        </div>
    </footer>
    <script src="{{ url_for('static', filename='js/jquery-3.5.1.js') }}"></script>
    <script src="{{ url_for('static', filename='js/bootstrap.min.js') }}"></script>
    <script src="{{ url_for('static', filename='js/slide.js') }}"></script>
    {% block script %}
    {% endblock %}
</body>
</html>

elice_library/templates/bookinfo.html
{% extends 'base.html' %}
{% block content %}
<div class="min-h-screen bg-gray-200">  
  <div class=" w-100 min-h-full"> 
    <div class="flex flex-col items-center w-full">
      <div class="flex w-full items-center justify-between border-2 bg-white p-10 pr-40 pl-40 m-3">
        <img class="h-80" src="../{{ book_info.image_path }}" style="height:300px;">
        <table class="border-2">
          <tr>
            <th>책이름</th>
            <td>{{ book_info.bookname }}</td>
          </tr>
          <tr>
            <th>출판사</th>
            <td>{{ book_info.publisher }}</td>
          </tr>
          <tr>
            <th>저자</th>
            <td>{{ book_info.author }}</td>
          </tr>
          <tr>
            <th>출간일</th>
            <td>{{ book_info.published_date|datetime }}</td>
          </tr>
          <tr>
            <th>페이지수</th>
            <td>{{ book_info.pages }}</td>
          </tr>
          <tr>
            <th>ISBN 코드</th>
            <td>{{ book_info.isbn }}</td>
          </tr>
          <tr>
            <th>평균 평점</th>
            <td>{{ '%.2f' %(rating_avg/2) }}</td>
          </tr>
        </table>
      </div>
      <div class="p-10 bg-white">
        <h1 class="text-2xl">책소개</h1>
        <div class="mt-5">
          <p>{{book_info.description}}</p>
        </div>

        <!-- 댓글 목록 -->
        <h2 class="text-2xl mt-2">댓글</h2>
        {% if book_info.comment_set|length > 0 %}
        <div class="mt-3">
        {% for comment in comment_set %}
          <!-- 댓글 작성시 스크롤초기화 방지 -->
          <a name="comment_{{ comment.id }}"></a>
          <div style="border-top:1px solid #ddd;">
            <div class="comment py-2 text-muted" style="display: inline-block;">
              <span style="white-space:pre-line;">{{ comment.content }}</span>
            </div>
            <div class="comment py-2 text-muted" style="text-align: right;display:inline-block;position:absolute;right:7%;">
              {% for i in range(comment.rating//2) %}
                <img src="../../static/images/full_star.png" style="display: inline-block;width:20px;">
              {% endfor %}
              {% for i in range(comment.rating%2) %}
                <img src="../../static/images/half_star.png" style="display: inline-block;width:20px;">
              {% endfor %}
              {% for i in range((10-comment.rating)//2) %}
                <img src="../../static/images/empty_star.png" style="display: inline-block;width:20px;">
              {% endfor %}
              <span>
                - {{ comment.user.username }}, {{ comment.create_date|datetime }}
                {% if comment.modify_date %}
                (수정:{{ comment.modify_date|datetime }})
                {% endif %}
              </span>
              {% if g.user == comment.user %}
              <a href="{{ url_for('comment.modify', comment_id=comment.id) }}" class="small">수정</a>
              <a href="#" class="small delete" data-uri="{{ url_for('comment.delete', comment_id=comment.id) }}">삭제</a>
              {% endif %}
            </div>
          </div>
          {% endfor %}
        </div>
        {% endif %}
        <br/>
        <!-- 댓글 목록 End -->

        <!-- 댓글 작성 -->
        <div class="container my-3">
          <h5 class="border-bottom pb-2">댓글등록하기</h5>
          <form method="post" class="post-form my-3">
            {{ form.csrf_token }}
            {% include "form_errors.html" %}
            <div class="form-group">
                <label for="content">댓글내용</label>
                <textarea class="form-control" name="content" id="content" rows="3">{{ form.content.data or '' }}</textarea> 
            </div>
            <fieldset class="rate" style="color:rgb(220, 220, 220);">
              <input type="radio" id="rating10" name="rating" value="10" /><label for="rating10" title="5 stars"></label>
              <input type="radio" id="rating9" name="rating" value="9" /><label class="half" for="rating9" title="4 1/2 stars"></label>
              <input type="radio" id="rating8" name="rating" value="8" /><label for="rating8" title="4 stars"></label>
              <input type="radio" id="rating7" name="rating" value="7" /><label class="half" for="rating7" title="3 1/2 stars"></label>
              <input type="radio" id="rating6" name="rating" value="6" /><label for="rating6" title="3 stars"></label>
              <input type="radio" id="rating5" name="rating" value="5" /><label class="half" for="rating5" title="2 1/2 stars"></label>
              <input type="radio" id="rating4" name="rating" value="4" /><label for="rating4" title="2 stars"></label>
              <input type="radio" id="rating3" name="rating" value="3" /><label class="half" for="rating3" title="1 1/2 stars"></label>
              <input type="radio" id="rating2" name="rating" value="2" /><label for="rating2" title="1 star"></label>
              <input type="radio" id="rating1" name="rating" value="1" checked /><label class="half" for="rating1" title="1/2 star"></label>
              <!-- <input type="radio" id="rating0" name="rating" value="0" /><label for="rating0" title="No star"></label> -->
            </fieldset>
            <button type="submit" class="btn btn-primary">작성하기</button>
          </form>
      </div>
        <!-- <form method="post" class="mt-2">
          <textarea class="border-2 w-full" name="content"></textarea>
          <div style="border:1px solid black; width:300px;">
            <input type="text" name="rating"/>
          </div>
          <button
              class="float-right py-2 px-4 bg-purple-500 text-white font-semibold rounded-lg shadow-md focus:outline-none">
            작성하기
          </button>
        </form> -->
      </div>
    </div>
  </div>
</div>
{% endblock %}

{% block script %}
<script type='text/javascript'>
  $(document).ready(function(){
    $(".delete").on('click', function(){
      if(confirm("정말로 삭제하시겠습니까?")){
        location.href = $(this).data('uri');
      }
    });
  });
</script>
{% endblock %}

elice_library/templates/form_errors.html
<!-- 필드 오류 -->
{% for field, errors in form.errors.items() %}
<div class="alert alert-danger" role="alert">
    <strong>{{ form[field].label }}</strong>: {{ ','.join(errors) }}
</div>
{% endfor %}
<!-- flash 오류 -->
{% for message in get_flashed_messages() %}
<div class="alert alert-danger" role="alert">
    {{ message }}
</div>
{% endfor %}

elice_library/templates/loggedin.html
{% extends 'base.html' %}
{% block content %}
<main>
  <div class="container" style="padding-top:30px;">
    <!-- 추천도서 -->
    <div style="width:60%;display:inline-block;">
      <section id="photo">
        <div class="slider">
            <div class="slide active" style="background:url('{{ book_recommend[0].image_path }}') no-repeat center;background-size:contain;"></div>
            <div class="slide" style="background:url('{{ book_recommend[1].image_path }}') no-repeat center;background-size:contain;"></div>
            <div class="slide" style="background:url('{{ book_recommend[2].image_path }}') no-repeat center;background-size:contain;"></div>
            <div class="slide" style="background:url('{{ book_recommend[3].image_path }}') no-repeat center;background-size:contain;"></div>
        </div>
        <p class="left-arrow" style="position:relative;display:inline-block;left:10%"></p>
        <p class="right-arrow" style="position:relative;display:inline-block;left:80%"></p>
      </section>
    </div>
    <div style="width:35%;display:inline-block;position:absolute;top:180px;">
      <h3 class="fw-light">추천도서</h3>
      <section id='recommend_info'>
        <div class="slide active">
          <table class="border-2">
            <tr>
              <th>책이름</th>
              <td>{{ book_recommend[0].bookname }}</td>
            </tr>
            <tr>
              <th>출판사</th>
              <td>{{ book_recommend[0].publisher }}</td>
            </tr>
            <tr>
              <th>저자</th>
              <td>{{ book_recommend[0].author }}</td>
            </tr>
              <th>페이지수</th>
              <td>{{ book_recommend[0].pages }}</td>
            </tr>
          </table>
          {% for i in range(book_recommend[0].rating//2) %}
            <img src="../static/images/full_star.png" style="display: inline-block;width:33px;">
          {% endfor %}
          {% for i in range(book_recommend[0].rating%2) %}
            <img src="../static/images/half_star.png" style="display: inline-block;width:33px;">
          {% endfor %}
          {% for i in range((10-book_recommend[0].rating)//2) %}
            <img src="../static/images/empty_star.png" style="display: inline-block;width:33px;">
          {% endfor %}
        </div>
        <div class="slide">
          <table class="border-2">
            <tr>
              <th>책이름</th>
              <td>{{ book_recommend[1].bookname }}</td>
            </tr>
            <tr>
              <th>출판사</th>
              <td>{{ book_recommend[1].publisher }}</td>
            </tr>
            <tr>
              <th>저자</th>
              <td>{{ book_recommend[1].author }}</td>
            </tr>
              <th>페이지수</th>
              <td>{{ book_recommend[1].pages }}</td>
            </tr>
          </table>
          {% for i in range(book_recommend[1].rating//2) %}
            <img src="../static/images/full_star.png" style="display: inline-block;width:33px;">
          {% endfor %}
          {% for i in range(book_recommend[1].rating%2) %}
            <img src="../static/images/half_star.png" style="display: inline-block;width:33px;">
          {% endfor %}
          {% for i in range((10-book_recommend[1].rating)//2) %}
            <img src="../static/images/empty_star.png" style="display: inline-block;width:33px;">
          {% endfor %}
        </div>
        <div class="slide">
          <table class="border-2">
            <tr>
              <th>책이름</th>
              <td>{{ book_recommend[2].bookname }}</td>
            </tr>
            <tr>
              <th>출판사</th>
              <td>{{ book_recommend[2].publisher }}</td>
            </tr>
            <tr>
              <th>저자</th>
              <td>{{ book_recommend[2].author }}</td>
            </tr>
              <th>페이지수</th>
              <td>{{ book_recommend[2].pages }}</td>
            </tr>
          </table>
          {% for i in range(book_recommend[2].rating//2) %}
            <img src="../static/images/full_star.png" style="display: inline-block;width:33px;">
          {% endfor %}
          {% for i in range(book_recommend[2].rating%2) %}
            <img src="../static/images/half_star.png" style="display: inline-block;width:33px;">
          {% endfor %}
          {% for i in range((10-book_recommend[2].rating)//2) %}
            <img src="../static/images/empty_star.png" style="display: inline-block;width:33px;">
          {% endfor %}
        </div>
        <div class="slide">
          <table class="border-2">
            <tr>
              <th>책이름</th>
              <td>{{ book_recommend[3].bookname }}</td>
            </tr>
            <tr>
              <th>출판사</th>
              <td>{{ book_recommend[3].publisher }}</td>
            </tr>
            <tr>
              <th>저자</th>
              <td>{{ book_recommend[3].author }}</td>
            </tr>
              <th>페이지수</th>
              <td>{{ book_recommend[3].pages }}</td>
            </tr>
          </table>
          {% for i in range(book_recommend[3].rating//2) %}
            <img src="../static/images/full_star.png" style="display: inline-block;width:33px;">
          {% endfor %}
          {% for i in range(book_recommend[3].rating%2) %}
            <img src="../static/images/half_star.png" style="display: inline-block;width:33px;">
          {% endfor %}
          {% for i in range((10-book_recommend[3].rating)//2) %}
            <img src="../static/images/empty_star.png" style="display: inline-block;width:33px;">
          {% endfor %}
        </div>
      </section>
    </div> 
    <!-- 추천도서 끝 -->
  </div>
  <div class="album py-5 bg-light">
    <div class="container">
      <div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 g-3" style="--bs-gutter-y: -2rem;">
        <!-- Pagination 객체로 변경되었으므로 book_list를 book_list.items로 변경 -->
        {% for book in book_list.items %}
        <div class="col" style="width:25%;">
          <div class="card shadow-sm" style="height:90%">
            <img src="{{ book.image_path }}" style="height:65%;">
            <div class="card-body" style="height:35%;">
              <p class="card-text" style="height:30%"><a href="/book/{{ book.id }}">{{ book.bookname }}</a></p>
              <div>
                {% for i in range(book.rating//2) %}
                <img src="../static/images/full_star.png" style="display: inline-block;width:33px;">
                {% endfor %}
                {% for i in range(book.rating%2) %}
                <img src="../static/images/half_star.png" style="display: inline-block;width:33px;">
                {% endfor %}
                {% for i in range((10-book.rating)//2) %}
                <img src="../static/images/empty_star.png" style="display: inline-block;width:33px;">
                {% endfor %}
                <div class="d-flex justify-content-between align-items-center" style="margin-top:10px">
                  <div class="btn-group">
                    <form action = "/" method="POST">
                      <input type="hidden" name = "book_id" value = "{{ book.id }}">
                      <button class="btn btn-sm btn-outline-secondary">대여하기</button>
                      <!-- <button>요소 자체는 submit속성을 지니고 있기 때문에 type 정의가 되어있지 않다면 submit 동작을 한다. -->
                    </form>
                  </div>
                  <small class="text-muted">남은책수 : {{ book.stock }}</small>
                </div>
              </div>
            </div>
          </div>
        </div>
        {% endfor %}
      </div>
    </div>
    <!-- 페이징처리 시작 -->
  <ul class="pagination justify-content-center">
    <li class="page-item">
      <a class="page-link" href="?page=1">처음</a>
    </li>
    <!-- 이전페이지 -->
    {% if book_list.has_prev %}
    <li class="page-item">
        <a class="page-link" href="?page={{ book_list.prev_num }}">이전</a>
    </li>
    {% else %}
    <li class="page-item disabled">
        <a class="page-link" tabindex="-1" aria-disabled="true" href="#">이전</a>
    </li>
    {% endif %}
    {% for page_num in book_list.iter_pages() %}
        {% if page_num %}
            {% if page_num != book_list.page %}
            <li class="page-item">
                <a class="page-link" href="?page={{ page_num }}">{{ page_num }}</a>
            </li>
            {% else %}
            <li class="page-item active" aria-current="page">
                <a class="page-link" href="#">{{ page_num }}</a>
            </li>
            {% endif %}
        {% else %}
            <li class="disabled">
                <a class="page-link" href="#">...</a>
            </li>
        {% endif %}
    {% endfor %}
    <!-- 다음페이지 -->
    {% if book_list.has_next %}
    <li class="page-item">
        <a class="page-link" href="?page={{ book_list.next_num }}">다음</a>
    </li>
    {% else %}
    <li class="page-item disabled">
        <a class="page-link" tabindex="-1" aria-disabled="true" href="#">다음</a>
    </li>
    {% endif %}
    <li class="page-item">
      {% if (book_list.total%book_list.per_page) == 0 %}
      <a class="page-link" href="?page={{ (book_list.total//book_list.per_page) }}">끝</a>
      {% else %}
      <a class="page-link" href="?page={{ (book_list.total//book_list.per_page)+1 }}">끝</a>
      {% endif %}
    </li>
  </ul>
  <!-- 페이징처리 끝 -->
  </div>
</main>
<!-- 남은 책 없을 때 경고 메시지 -->
{% with messages = get_flashed_messages() %}
  {% if messages %}
    {% for message in messages %}
      <script>
        alert('{{message}}')
      </script>
    {% endfor %}
  {% endif %}
{% endwith %}
{% endblock %}

elice_library/templates/rental.html
{% extends 'base.html' %}
{% block content %}
<main>
    <div class="album py-5 bg-light">
        <div class="container">
    
          <div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 g-3">
            {% for rental_info in rental_list %}
            <div class="col" style="width:25%;">
              <div class="card shadow-sm" style="height:90%">
                <img src="{{ rental_info.book.image_path }}" style="height:70%;">
                <div class="card-body" style="height:30%;">
                  <p class="card-text" style="height:40%;"><a href="/book/{{ rental_info.book_id }}">{{ rental_info.book.bookname }}</a></p>
                  <div class="d-flex justify-content-between align-items-center">
                    <div class="btn-group">
                    </div>
                    {% if rental_info.return_date != None %}
                    <small class="text-muted">대여날짜: {{ rental_info.rental_date|datetime }} ~ {{ rental_info.return_date|datetime }}</small>
                    {% elif rental_info.return_date == None %}
                    <small class="text-muted">대여날짜: {{ rental_info.rental_date|datetime }} ~ </small>
                    {% endif %}
                  </div>
                </div>
              </div>
            </div>
            {% endfor %}
          </div>
        </div>
      </div>
</main>
{% endblock %}